using System.Collections.Generic;

namespace Pixelfactor.IP.SavedGames.V2.Model
{
    /// <summary>
    /// This helper map is populated for ships only
    /// </summary>
    public static class ComponentBayMap
    {
        public static Dictionary<ModelUnitClass, List<ModelComponentBay>> UnitClassComponentBays { get; } = new Dictionary<ModelUnitClass, List<ModelComponentBay>>();

        static ComponentBayMap()
        {
            AddBay((ModelUnitClass)50, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)50, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)300, Name = "Countermeasure" });
            AddBay((ModelUnitClass)50, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)50, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)50, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)50, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)50, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)50, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)50, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)50, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield" });
            AddBay((ModelUnitClass)50, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)50, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)0, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)0, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)300, Name = "Countermeasure" });
            AddBay((ModelUnitClass)0, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)0, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)0, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)0, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)0, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)0, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)0, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)0, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield" });
            AddBay((ModelUnitClass)0, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)0, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)100, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)100, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)100, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)300, Name = "Countermeasure" });
            AddBay((ModelUnitClass)100, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)100, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)100, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)100, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)100, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)100, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)100, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)100, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield" });
            AddBay((ModelUnitClass)100, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)100, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)8001, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)8001, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)8001, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)8001, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)8001, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Rear Lower Turret" });
            AddBay((ModelUnitClass)8001, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)8001, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)8001, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Rear Upper Turret" });
            AddBay((ModelUnitClass)8001, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1100, Name = "Shield" });
            AddBay((ModelUnitClass)8001, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)8001, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module " });
            AddBay((ModelUnitClass)9000, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)9000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)9000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine" });
            AddBay((ModelUnitClass)9000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)9000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)9000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)9000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)9000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Rear Lower Turret" });
            AddBay((ModelUnitClass)9000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Rear Upper Turret" });
            AddBay((ModelUnitClass)9000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1100, Name = "Shield" });
            AddBay((ModelUnitClass)9000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)8000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)8000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)8000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)8000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)8000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Rear Lower Turret" });
            AddBay((ModelUnitClass)8000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)8000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)8000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Rear Upper Turret" });
            AddBay((ModelUnitClass)8000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1100, Name = "Shield" });
            AddBay((ModelUnitClass)8000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)8000, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module " });
            AddBay((ModelUnitClass)38000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)38000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)38000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)38000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Left Turret" });
            AddBay((ModelUnitClass)38000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Main Turret" });
            AddBay((ModelUnitClass)38000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Right Turret" });
            AddBay((ModelUnitClass)38000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)38000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)38000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)38000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)38000, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)38000, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)39000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)39000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)39000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)39000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Left Turret" });
            AddBay((ModelUnitClass)39000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Main Turret" });
            AddBay((ModelUnitClass)39000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)39000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Right Turret" });
            AddBay((ModelUnitClass)39000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)39000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)39000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)39000, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)39000, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)11000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)11000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)300, Name = "Countermeasure" });
            AddBay((ModelUnitClass)11000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)500, Name = "Engine" });
            AddBay((ModelUnitClass)11000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Left Turret" });
            AddBay((ModelUnitClass)11000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)11000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)700, Name = "Mine" });
            AddBay((ModelUnitClass)11000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)11000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)11000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Right Turret" });
            AddBay((ModelUnitClass)11000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield" });
            AddBay((ModelUnitClass)11000, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)11000, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)12000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)12000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)300, Name = "Countermeasure" });
            AddBay((ModelUnitClass)12000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)500, Name = "Engine" });
            AddBay((ModelUnitClass)12000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Left Turret" });
            AddBay((ModelUnitClass)12000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)12000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)700, Name = "Mine" });
            AddBay((ModelUnitClass)12000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)12000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)12000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Right Turret" });
            AddBay((ModelUnitClass)12000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield" });
            AddBay((ModelUnitClass)12000, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)12000, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)13000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)13000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine" });
            AddBay((ModelUnitClass)13000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)1300, Name = "Left Turret" });
            AddBay((ModelUnitClass)13000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)300, Name = "Countermeasure" });
            AddBay((ModelUnitClass)13000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Right Turret" });
            AddBay((ModelUnitClass)13000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)700, Name = "Mine Bay" });
            AddBay((ModelUnitClass)13000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)13000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)13000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)13000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)13000, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)13000, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)15010, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)15010, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)15010, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)1300, Name = "Front Turret" });
            AddBay((ModelUnitClass)15010, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)15010, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)15010, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)15010, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)15010, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)700, Name = "Mine Bay" });
            AddBay((ModelUnitClass)15010, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)15010, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)15010, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)15010, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics Bay" });
            AddBay((ModelUnitClass)15010, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)14000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)14000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)14000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)1300, Name = "Front Turret" });
            AddBay((ModelUnitClass)14000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)14000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)14000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)14000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)14000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)700, Name = "Mine Bay" });
            AddBay((ModelUnitClass)14000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)14000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)14000, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)14000, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics Bay" });
            AddBay((ModelUnitClass)14000, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)15000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)15000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)15000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)1300, Name = "Front Turret" });
            AddBay((ModelUnitClass)15000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)15000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)15000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)15000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)15000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)700, Name = "Mine Bay" });
            AddBay((ModelUnitClass)15000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)15000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)15000, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)15000, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics Bay" });
            AddBay((ModelUnitClass)15000, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)15100, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)15100, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)15100, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)1300, Name = "Front Turret" });
            AddBay((ModelUnitClass)15100, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)15100, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)15100, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)15100, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)700, Name = "Mine Bay" });
            AddBay((ModelUnitClass)15100, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)15100, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)15100, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)15100, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics Bay" });
            AddBay((ModelUnitClass)15100, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)16000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)16000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)16000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)16000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1400, Name = "Front Mining Turret" });
            AddBay((ModelUnitClass)16000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1400, Name = "Mid Mining Turret" });
            AddBay((ModelUnitClass)16000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)16000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)700, Name = "Mine Bay" });
            AddBay((ModelUnitClass)16000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)16000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)16000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)16000, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)16000, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics Bay" });
            AddBay((ModelUnitClass)40000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)40000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)40000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)40000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Left Turret" });
            AddBay((ModelUnitClass)40000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)700, Name = "Mine" });
            AddBay((ModelUnitClass)40000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Right Turret" });
            AddBay((ModelUnitClass)40000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)40000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)40000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)40000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)40000, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)41000, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)41000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)41000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)41000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)41000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Left Turret" });
            AddBay((ModelUnitClass)41000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)700, Name = "Mine" });
            AddBay((ModelUnitClass)41000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Right Turret" });
            AddBay((ModelUnitClass)41000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)41000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)41000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)41000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)41003, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)41003, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)41003, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)41003, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)41003, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Left Turret" });
            AddBay((ModelUnitClass)41003, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)700, Name = "Mine" });
            AddBay((ModelUnitClass)41003, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Right Turret" });
            AddBay((ModelUnitClass)41003, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)41003, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)41003, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)41003, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)22010, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)22010, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)22010, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)22010, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)22010, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Main Turret" });
            AddBay((ModelUnitClass)22010, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)22010, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Turret" });
            AddBay((ModelUnitClass)22010, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)22010, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Rear Left Turret" });
            AddBay((ModelUnitClass)22010, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)22010, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1300, Name = "Rear Right Turret" });
            AddBay((ModelUnitClass)22010, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)22010, new ModelComponentBay { Id = 13, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)22010, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)22000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)22000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)22000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)22000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)22000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Main Turret" });
            AddBay((ModelUnitClass)22000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)22000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Turret" });
            AddBay((ModelUnitClass)22000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)22000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Rear Left Turret" });
            AddBay((ModelUnitClass)22000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)22000, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1300, Name = "Rear Right Turret" });
            AddBay((ModelUnitClass)22000, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)22000, new ModelComponentBay { Id = 13, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)22000, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)22050, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)22050, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)22050, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)22050, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)22050, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)22050, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Turret" });
            AddBay((ModelUnitClass)22050, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)22050, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Rear Left Turret" });
            AddBay((ModelUnitClass)22050, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)22050, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1300, Name = "Rear Right Turret" });
            AddBay((ModelUnitClass)22050, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)22050, new ModelComponentBay { Id = 13, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)22050, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)22005, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)22005, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)22005, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)22005, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Main Turret" });
            AddBay((ModelUnitClass)22005, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)22005, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Turret" });
            AddBay((ModelUnitClass)22005, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)22005, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Rear Left Turret" });
            AddBay((ModelUnitClass)22005, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)22005, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1300, Name = "Rear Right Turret" });
            AddBay((ModelUnitClass)22005, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)22005, new ModelComponentBay { Id = 13, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)22005, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)22005, new ModelComponentBay { Id = 200, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)55010, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)55010, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)300, Name = "Countermeasure" });
            AddBay((ModelUnitClass)55010, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)55010, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)55010, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)55010, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)700, Name = "Mine Turret" });
            AddBay((ModelUnitClass)55010, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)55010, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Left Turret" });
            AddBay((ModelUnitClass)55010, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)55010, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield" });
            AddBay((ModelUnitClass)55010, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)55010, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)55010, new ModelComponentBay { Id = 200, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)55010, new ModelComponentBay { Id = 110, Type = (ModelComponentBayType)1300, Name = "Top Right Turret" });
            AddBay((ModelUnitClass)55000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)55000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)300, Name = "Countermeasure" });
            AddBay((ModelUnitClass)55000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)55000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)55000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)55000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)700, Name = "Mine Turret" });
            AddBay((ModelUnitClass)55000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)55000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Left Turret" });
            AddBay((ModelUnitClass)55000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)55000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield" });
            AddBay((ModelUnitClass)55000, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)55000, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)55000, new ModelComponentBay { Id = 200, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)55000, new ModelComponentBay { Id = 110, Type = (ModelComponentBayType)1300, Name = "Top Right Turret" });
            AddBay((ModelUnitClass)55005, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)55005, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)300, Name = "Countermeasure" });
            AddBay((ModelUnitClass)55005, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)55005, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)55005, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)55005, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)700, Name = "Mine Turret" });
            AddBay((ModelUnitClass)55005, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)55005, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Left Turret" });
            AddBay((ModelUnitClass)55005, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)55005, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield" });
            AddBay((ModelUnitClass)55005, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)55005, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)55005, new ModelComponentBay { Id = 200, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)55005, new ModelComponentBay { Id = 110, Type = (ModelComponentBayType)1300, Name = "Top Right Turret" });
            AddBay((ModelUnitClass)25010, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)25010, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)25010, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)25010, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)25010, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Rear Left Turret" });
            AddBay((ModelUnitClass)25010, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)25010, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)25010, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Lower Mid Turret" });
            AddBay((ModelUnitClass)25010, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)25010, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)25010, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1300, Name = "Rear Right Turret" });
            AddBay((ModelUnitClass)25010, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)25010, new ModelComponentBay { Id = 13, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)25010, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)25000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)25000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)25000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)25000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)25000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Rear Left Turret" });
            AddBay((ModelUnitClass)25000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)25000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)25000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Lower Mid Turret" });
            AddBay((ModelUnitClass)25000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)25000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)25000, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1300, Name = "Rear Right Turret" });
            AddBay((ModelUnitClass)25000, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)25000, new ModelComponentBay { Id = 13, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)25000, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)25003, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)25003, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)25003, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)25003, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)25003, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)25003, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)25003, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)25003, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Lower Mid Turret" });
            AddBay((ModelUnitClass)25003, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)25003, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)25003, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)25003, new ModelComponentBay { Id = 13, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)25003, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)25003, new ModelComponentBay { Id = 200, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)26000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)26000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)26000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)26000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Left Turret" });
            AddBay((ModelUnitClass)26000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)700, Name = "Mine" });
            AddBay((ModelUnitClass)26000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)26000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Right Turret" });
            AddBay((ModelUnitClass)26000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)26000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)26000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)26000, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)26000, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)26000, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)27000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)27000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)27000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)27000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Left Turret" });
            AddBay((ModelUnitClass)27000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)700, Name = "Mine" });
            AddBay((ModelUnitClass)27000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)27000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Right Turret" });
            AddBay((ModelUnitClass)27000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)27000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)27000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)27000, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)27000, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)27000, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)28000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)28000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)28000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)28000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Left Turret" });
            AddBay((ModelUnitClass)28000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)700, Name = "Mine" });
            AddBay((ModelUnitClass)28000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)28000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Right Turret" });
            AddBay((ModelUnitClass)28000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)28000, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)28000, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)28000, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)28000, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)28000, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)600, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)600, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)600, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)600, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Main Turret" });
            AddBay((ModelUnitClass)600, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)600, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)600, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)600, new ModelComponentBay { Id = 16, Type = (ModelComponentBayType)700, Name = "Mine Bay" });
            AddBay((ModelUnitClass)600, new ModelComponentBay { Id = 20, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)620, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)620, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)620, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)620, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Main Turret" });
            AddBay((ModelUnitClass)620, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)620, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)620, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)620, new ModelComponentBay { Id = 16, Type = (ModelComponentBayType)700, Name = "Mine Bay" });
            AddBay((ModelUnitClass)620, new ModelComponentBay { Id = 20, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)625, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)625, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)625, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)625, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)625, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)625, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)625, new ModelComponentBay { Id = 16, Type = (ModelComponentBayType)700, Name = "Mine Bay" });
            AddBay((ModelUnitClass)625, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Main Turret" });
            AddBay((ModelUnitClass)630, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)630, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)630, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)630, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1400, Name = "Main Mining Turret" });
            AddBay((ModelUnitClass)630, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)630, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)630, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)630, new ModelComponentBay { Id = 16, Type = (ModelComponentBayType)700, Name = "Mine Bay" });
            AddBay((ModelUnitClass)630, new ModelComponentBay { Id = 20, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)800, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)800, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)800, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)800, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)800, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)800, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)800, new ModelComponentBay { Id = 16, Type = (ModelComponentBayType)700, Name = "Mine Bay" });
            AddBay((ModelUnitClass)800, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)800, new ModelComponentBay { Id = 150, Type = (ModelComponentBayType)1300, Name = "Left Turret" });
            AddBay((ModelUnitClass)800, new ModelComponentBay { Id = 120, Type = (ModelComponentBayType)1300, Name = "Right Turret" });
            AddBay((ModelUnitClass)820, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)820, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)820, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)820, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)820, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)820, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)820, new ModelComponentBay { Id = 16, Type = (ModelComponentBayType)700, Name = "Mine Bay" });
            AddBay((ModelUnitClass)820, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)820, new ModelComponentBay { Id = 150, Type = (ModelComponentBayType)1300, Name = "Left Turret" });
            AddBay((ModelUnitClass)820, new ModelComponentBay { Id = 120, Type = (ModelComponentBayType)1300, Name = "Right Turret" });
            AddBay((ModelUnitClass)35000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)35000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)35000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)35000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Left Turret" });
            AddBay((ModelUnitClass)35000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Right Turret" });
            AddBay((ModelUnitClass)35000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)35000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)35000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)35000, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)36000, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)36000, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)36000, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)36000, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)36000, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Left Turret" });
            AddBay((ModelUnitClass)36000, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Right Turret" });
            AddBay((ModelUnitClass)36000, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)36000, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)36000, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)55505, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)55505, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)300, Name = "Countermeasure" });
            AddBay((ModelUnitClass)55505, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)55505, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)55505, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)55505, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)700, Name = "Mine Turret" });
            AddBay((ModelUnitClass)55505, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)55505, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)55505, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield" });
            AddBay((ModelUnitClass)55505, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)55505, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)55505, new ModelComponentBay { Id = 200, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)55505, new ModelComponentBay { Id = 300, Type = (ModelComponentBayType)1300, Name = "Rear Left Turret" });
            AddBay((ModelUnitClass)55505, new ModelComponentBay { Id = 400, Type = (ModelComponentBayType)1300, Name = "Rear Right Turret" });
            AddBay((ModelUnitClass)55500, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)55500, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)300, Name = "Countermeasure" });
            AddBay((ModelUnitClass)55500, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)55500, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)55500, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)55500, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)700, Name = "Mine Turret" });
            AddBay((ModelUnitClass)55500, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)55500, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)55500, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield" });
            AddBay((ModelUnitClass)55500, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)55500, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)55500, new ModelComponentBay { Id = 200, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)55500, new ModelComponentBay { Id = 300, Type = (ModelComponentBayType)1300, Name = "Rear Left Turret" });
            AddBay((ModelUnitClass)55500, new ModelComponentBay { Id = 400, Type = (ModelComponentBayType)1300, Name = "Rear Right Turret" });
            AddBay((ModelUnitClass)55503, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)55503, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)300, Name = "Countermeasure" });
            AddBay((ModelUnitClass)55503, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)55503, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Left Turret" });
            AddBay((ModelUnitClass)55503, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1300, Name = "Front Right Turret" });
            AddBay((ModelUnitClass)55503, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)700, Name = "Mine Turret" });
            AddBay((ModelUnitClass)55503, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)55503, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)55503, new ModelComponentBay { Id = 10, Type = (ModelComponentBayType)1100, Name = "Shield" });
            AddBay((ModelUnitClass)55503, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)55503, new ModelComponentBay { Id = 100, Type = (ModelComponentBayType)900, Name = "Passenger Module" });
            AddBay((ModelUnitClass)55503, new ModelComponentBay { Id = 200, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)55503, new ModelComponentBay { Id = 300, Type = (ModelComponentBayType)1300, Name = "Rear Left Turret" });
            AddBay((ModelUnitClass)55503, new ModelComponentBay { Id = 400, Type = (ModelComponentBayType)1300, Name = "Rear Right Turret" });
            AddBay((ModelUnitClass)700, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)700, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)700, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)700, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Turret" });
            AddBay((ModelUnitClass)700, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)700, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)700, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)700, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)700, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)700, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)700, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)700, new ModelComponentBay { Id = 30, Type = (ModelComponentBayType)700, Name = "Mine Bay" });
            AddBay((ModelUnitClass)710, new ModelComponentBay { Id = 1, Type = (ModelComponentBayType)100, Name = "Capacitor" });
            AddBay((ModelUnitClass)710, new ModelComponentBay { Id = 2, Type = (ModelComponentBayType)500, Name = "Engine Bay" });
            AddBay((ModelUnitClass)710, new ModelComponentBay { Id = 3, Type = (ModelComponentBayType)300, Name = "Countermeasure Bay" });
            AddBay((ModelUnitClass)710, new ModelComponentBay { Id = 4, Type = (ModelComponentBayType)1300, Name = "Front Turret" });
            AddBay((ModelUnitClass)710, new ModelComponentBay { Id = 5, Type = (ModelComponentBayType)1300, Name = "Mid Turret" });
            AddBay((ModelUnitClass)710, new ModelComponentBay { Id = 6, Type = (ModelComponentBayType)1300, Name = "Top Turret" });
            AddBay((ModelUnitClass)710, new ModelComponentBay { Id = 7, Type = (ModelComponentBayType)1000, Name = "Power Generator" });
            AddBay((ModelUnitClass)710, new ModelComponentBay { Id = 8, Type = (ModelComponentBayType)1300, Name = "Rear Turret" });
            AddBay((ModelUnitClass)710, new ModelComponentBay { Id = 9, Type = (ModelComponentBayType)1100, Name = "Shield Bay" });
            AddBay((ModelUnitClass)710, new ModelComponentBay { Id = 11, Type = (ModelComponentBayType)1200, Name = "Tractor Beam" });
            AddBay((ModelUnitClass)710, new ModelComponentBay { Id = 12, Type = (ModelComponentBayType)400, Name = "Electronics" });
            AddBay((ModelUnitClass)710, new ModelComponentBay { Id = 30, Type = (ModelComponentBayType)700, Name = "Mine Bay" });
        }

        public static IEnumerable<ModelComponentBay> GetComponentBays(ModelUnitClass unitClass)
        {
            List<ModelComponentBay> bays = null;
            if (!UnitClassComponentBays.TryGetValue(unitClass, out bays))
            {
                bays = new List<ModelComponentBay>();
            }

            return bays;
        }

        private static void AddBay(ModelUnitClass unitClass, ModelComponentBay componentBay)
        {
            List<ModelComponentBay> bays = null;
            if (!UnitClassComponentBays.TryGetValue(unitClass, out bays))
            {
                bays = new List<ModelComponentBay>();
                UnitClassComponentBays[unitClass] = bays;
            }

            bays.Add(componentBay);
        }
    }
}
